// Generated by CoffeeScript 1.9.3
var getTime, update;

$().ready(function() {
  if ($.cookie('maxStm') != null) {
    $('#maxStm').val($.cookie('maxStm'));
  }
  $('#maxStm').on('change', function() {
    $.cookie('maxStm', $(this).val(), {
      expires: 365 * 100
    });
    return update();
  });
  $('#nowStm').on('change', function() {
    $('#nowStmInputTime').val(getTime());
    return update();
  });
  return setInterval(update, 1000);
});

update = function() {
  var atStr, inputDate, inputTime, maxDate, maxStm, nowStm, reqSec, reqStr;
  inputTime = Number($('#nowStmInputTime').val());
  if (inputTime === 0) {
    return;
  }
  inputTime;
  maxStm = Number($('#maxStm').val());
  nowStm = Number($('#nowStm').val());
  reqSec = (maxStm - nowStm) * 60 * 5;
  reqStr = '';
  reqStr += reqSec >= 60 * 60 ? '' + Math.floor(reqSec / 60 / 60) + ' 時間' : '';
  reqStr += reqSec >= 60 && Math.floor(reqSec / 60 % 60) !== 0 ? '' + Math.floor(reqSec / 60 % 60) + ' 分' : '';
  reqStr = reqStr === '' ? ' スタミナ消化しろ' : reqStr;
  $('#reqStr').html(reqStr);
  inputDate = new Date(inputTime * 1000);
  maxDate = new Date((inputTime + reqSec) * 1000);
  atStr = '';
  if (reqSec <= 0) {
    atStr += '既';
  } else {
    atStr += maxDate.getDate() !== inputDate.getDate() ? '明日 ' : '今日 ';
    atStr += ('0' + maxDate.getHours()).slice(-2) + ':' + ('0' + maxDate.getMinutes()).slice(-2);
  }
  return $('#atStr').html(atStr);
};

getTime = function() {
  return Math.floor(+new Date() / 1000);
};
