// Generated by CoffeeScript 1.9.3
var date4google, getLink4google, getTime, update, zerofill;

$().ready(function() {
  var hide, show;
  if ($.cookie('maxStm') != null) {
    $('#maxStm').val($.cookie('maxStm'));
  }
  $('#maxStm').on('change', function() {
    $.cookie('maxStm', $(this).val(), {
      expires: 365 * 100
    });
    return update();
  });
  $('#nowStm').on('change', function() {
    $('#nowStmInputTime').val(getTime());
    return update();
  });
  $('#googleCalendar').on('click', function() {
    var date;
    if (+new Date($('#calendarDate').val() < +new Date())) {
      return;
    }
    date = new Date(Number($('#calendarDate').val()));
    return window.open(getLink4google(date));
  });
  setInterval(update, 1000);
  show = 'QRコードを表示する';
  hide = 'QRコードを非表示にする';
  $('#qrbutton').on('click', (function(_this) {
    return function() {
      if ($('#qrbutton').text() === show) {
        $('#qrbutton').text(hide);
      } else {
        $('#qrbutton').text(show);
      }
      return $('#code').slideToggle();
    };
  })(this));
  $('#code').qrcode({
    render: "table",
    text: location.href
  });
  return $('#qrbutton').text(show);
});

update = function() {
  var atStr, inputDate, inputTime, maxDate, maxStm, nowStm, reqSec, reqStr;
  inputTime = Number($('#nowStmInputTime').val());
  if (inputTime === 0) {
    return;
  }
  inputTime;
  maxStm = Number($('#maxStm').val());
  nowStm = Number($('#nowStm').val());
  reqSec = (maxStm - nowStm) * 60 * 5;
  reqStr = '';
  reqStr += reqSec >= 60 * 60 ? '' + Math.floor(reqSec / 60 / 60) + ' 時間' : '';
  reqStr += reqSec >= 60 && Math.floor(reqSec / 60 % 60) !== 0 ? '' + Math.floor(reqSec / 60 % 60) + ' 分' : '';
  reqStr = reqStr === '' ? ' はやく消化しなきゃ' : reqStr;
  $('#reqStr').html(reqStr);
  inputDate = new Date(inputTime * 1000);
  maxDate = new Date((inputTime + reqSec) * 1000);
  atStr = '';
  if (reqSec <= 0) {
    atStr += 'もう時間だ';
  } else {
    atStr += maxDate.getDate() !== inputDate.getDate() ? '明日 ' : '今日 ';
    atStr += zerofill(maxDate.getHours()) + ':' + zerofill(maxDate.getMinutes());
  }
  $('#atStr').html(atStr);
  return $('#calendarDate').val(+maxDate);
};

getLink4google = function(date) {
  return 'http://www.google.com/calendar/event?' + 'action=' + 'TEMPLATE' + '&text=' + encodeURIComponent('デレステスタミナMAX') + '&details=' + encodeURIComponent('デレステのスタミナがMAXになった') + '&location=' + encodeURIComponent('アプリ') + '&dates=' + date4google(date) + '/' + date4google(date) + '&trp=' + 'false' + '&sprop=' + encodeURIComponent(location.href) + '&sprop=' + 'name:' + encodeURIComponent('デレステスタミナ計算機');
};

getTime = function() {
  return Math.floor(+new Date() / 1000);
};

date4google = function(date) {
  return date.getUTCFullYear() + zerofill(date.getUTCMonth() + 1) + zerofill(date.getUTCDate()) + 'T' + zerofill(date.getUTCHours()) + zerofill(date.getUTCMinutes()) + zerofill(date.getUTCSeconds()) + 'Z';
};

zerofill = function(num) {
  return ('0' + num).slice(-2);
};
